export const FETCH_TECHS_SUCCESS = 'FETCH_TECHS_SUCCESS';
export const FILTER_TECHS_SUCCESS = 'FILTER_TECHS_SUCCESS';
export const FETCHING_TECHS = 'FETCHING_TECHS';
export const ERROR_FETCH_TECHS = 'ERROR_FETCH_TECHS';
